# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/app" 
    target-branch: "main"
    schedule:
      interval: "daily"
    labels:
      - "all"
      - "dependencies"
    #ignore: # you can limit dependabot versions to minor upgrades
    #  - dependency-name: "*"
    #    update-types: ["version-update:semver-major"]
    groups: # you can group updates in one PR
       all: # Specify a name for the group, which will be used in pull request titles and branch names
          applies-to: version-updates
          patterns:
            - "*"

  # if we work on a distinct branch for major releases (ex. next-major)
  # we can create a separate dependabot configuration for major upgrades
  # excluding minor and patch upgrades