# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dependabot/**" ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up JDK 21
  #     uses: actions/setup-java@v4
  #     with:
  #       java-version: '21'
  #       distribution: 'temurin'
  #   # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
  #   # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
  #   - name: Setup Gradle
  #     uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
  #   - name: Build with Gradle Wrapper
  #     run: ./gradlew build

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up JDK 21
  #     uses: actions/setup-java@v4
  #     with:
  #       java-version: '21'
  #       distribution: 'temurin'
  #   # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
  #   # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
  #   - name: Setup Gradle
  #     uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
  #   - name: Test with Gradle Wrapper
  #     run: ./gradlew test

  #increment:
  #  #needs: test
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Dump GitHub context
  #    env:
  #      GITHUB_CONTEXT: ${{ toJson(github) }}
  #    run: echo "$GITHUB_CONTEXT"

  automerge: # if we we are on a dependabot branch fixing a minor version, we can merge it automatically
    #needs: increment
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'dependabot') && contains(github.head_ref, 'minors')
    steps:
    - uses: actions/checkout@v4
    - name: Print the branch name for traceability
      env:
        GITHUB_HEADREF: ${{ github.head_ref }}
      run: |
        echo "$GITHUB_HEADREF is a dependabot branch that can be merged automatically"
    - name: Tag the commit
      run: |
        git config user.name "Marc Campora"
        git config user.email "mcampora@ebsco.com"
        git checkout ${{ github.head_ref }}
        git branch --show-current
        git pull
        pwd
        ls -al
        git tag -f new_minor
        git push --follow-tags

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
